apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-db
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: stater
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: .
    repoURL: https://github.com/AmazingCluster/mongo-db-gitops
    targetRevision: HEAD
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true  