apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project.name }}
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: AppProject for the {{ .Values.project.name }} applications

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - https://github.com/AmazingCluster/*

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: {{ .Values.spec.destination.server }}

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true